/**
 * UniqueIdentifier.java
 * -----------------------------------------------------------------
 *     __ __ __  ___________ 
 *    / //_//  |/  /  _/ __ \	  .--.
 *   / ,<  / /|_/ // // /_/ /	 /.-. '----------.
 *  / /| |/ /  / // // ____/ 	 \'-' .--"--""-"-'
 * /_/ |_/_/  /_/___/_/      	  '--'
 * 
 * -----------------------------------------------------------------
 * Description:
 * The Unique Identifier is generated by the key management system 
 * to uniquely identify a Managed Object.
 *
 * @author     Stefanie Meile <stefaniemeile@gmail.com>
 * @author     Michael Guster <michael.guster@gmail.com>
 * @org.       NTB - University of Applied Sciences Buchs, (CH)
 * @copyright  Copyright � 2013, Stefanie Meile, Michael Guster
 * @license    Simplified BSD License (see LICENSE.TXT)
 * @version    1.0, 2013/08/09
 * @since      Class available since Release 1.0
 *
 * 
 */

package ch.ntb.inf.kmip.attributes;

import ch.ntb.inf.kmip.kmipenum.EnumTag;
import ch.ntb.inf.kmip.kmipenum.EnumType;
import ch.ntb.inf.kmip.objects.base.SingleAttribute;
import ch.ntb.inf.kmip.types.KMIPTextString;
import ch.ntb.inf.kmip.types.KMIPType;

public class UniqueIdentifier extends SingleAttribute<KMIPTextString> {

	public UniqueIdentifier(KMIPTextString value){
		super("Unique Identifier",
				new EnumTag(EnumTag.UniqueIdentifier),
				new EnumType(EnumType.TextString),
				value);
	}

	public UniqueIdentifier(String value) {
		this(new KMIPTextString(value));
	}

	public UniqueIdentifier(){
		this(new KMIPTextString());
	}

	public UniqueIdentifier(KMIPType value){
		this((KMIPTextString) value);
	}
}
